Clarify output notices.
When multiple notices are output, it needs to be more clear which step is producing them.

See https://github.com/newfold-labs/wp-module-sso/actions/runs/16026449635 for an example.

diff --git a/.github/workflows/reusable-translations.yml b/.github/workflows/reusable-translations.yml
--- a/.github/workflows/reusable-translations.yml
+++ b/.github/workflows/reusable-translations.yml
@@ -91,7 +91,7 @@ jobs:
         if: steps.check_pr.outputs.found != 'false'
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: gh pr update-branch --yes || echo "::notice::No new changes in $GITHUB_REF_NAME."
+        run: gh pr update-branch --yes || echo "::notice::No strings missing from POT file. in $GITHUB_REF_NAME."
 
       - name: Delete an orphaned branch with no pull request
         if: steps.check_pr.outputs.found == 'false' && steps.branch-check.outputs.exists == 'true'
@@ -369,7 +369,7 @@ jobs:
       - name: Stop the workflow run when no patch is found
         run: |
           if [ ! -s "$RUNNER_TEMP/updated-translations.diff" ]; then
-            echo "::info::No patch file found. No translation updates to commit."
+            echo "::notice::No patch file found. No translation updates to commit."
             exit 0
           fi
 
